# _config.yml
title: Blog Başlığı
description: Koyu tonlarda, pratik güncellenebilen GitHub Pages blog teması.
url: "https://sabriaydin.github.io"
baseurl: "/blog"

# Ana sayfada en fazla 5 içerik listelemek için sayfalama eklentisi
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5
paginate_path: "/page:num/"

future: true
